services:
  db:
    image: postgres:17
    container_name: shelfie_local_db
    environment:
      POSTGRES_USER: shelfie
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 'Shelfie1234!'
    ports:
      - '5432:5432'
    # Shared memory the container can use
    shm_size: 128mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  queues:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      # Management port
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: shelfie
      RABBITMQ_DEFAULT_PASS: Shelfie1234!

  ml:
    image: georgeshep/shelfie-ml

    ports:
      - '5241:5241'

    environment:
      PROCESSOR_PATH: 'src/trocr_local/processor'
      MODEL_PATH: 'src/trocr_local/model'
