services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: '${CLOUDFLARE_TOKEN}'
    depends_on:
      - api
      - shelfie
  api:
    image: georgeshep/bord:api.georgesheppard.dev
    platform: linux/amd64
    ports:
      - '5240:5240'
    env_file:
      - .env
    environment:
      NODE_ENV: 'production'
      PORT: '5240'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      RABBITMQ_HOST: 'queues'
      RABBITMQ_PORT: '5672'
    depends_on:
      db:
        condition: service_healthy
      queues:
        condition: service_healthy

  shelfie:
    image: jawil576/frontend:dev
    platform: linux/amd64

  db:
    image: postgres:17
    environment:
      # POSTGRES_PASSWORD: Without this line a random password is used
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_DB: '${DATABASE_DB}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    # Shared memory the container can use
    shm_size: 128mb
    volumes:
      # Persists the DB to ./pgdata
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  queues:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
    volumes:
      # Persists data to ./rabbitmq
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  scheduler:
    image: ubuntu:22.04
    container_name: scheduler
    restart: always
    depends_on:
      - api
    volumes:
      - ./cronjobs:/etc/cron.d
    command: /bin/bash -c "apt-get update && apt-get install -y curl cron && cron -f"
