name: PR Checks

on:
  pull_request:
    branches: ['master']

permissions:
  contents: write

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Generate OpenAPI Spec
        run: pnpm generate:openapi

      - name: Commit OpenAPI Spec if Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -z "$(git status --quiet generated/openapi/)" ]; then
            echo "No changes to OpenAPI spec"
          else
            git add generated/openapi/
            git commit -m "Generate OpenAPI spec"
            git push
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Integration Tests
        run: pnpm test:integration
