name: PR Checks

on:
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.22.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Load environment variables
        run: grep -v '^#' .env.test | grep -v '^$' >> $GITHUB_ENV

      - name: Run Integration Tests
        run: pnpm test:integration
